name: Tag Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags

      - name: Tag and push if new version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(jq -r .version package.json)
          TAG="v$VERSION"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. No action taken."
          else
            gh auth login --with-token < <(echo "$GH_TOKEN")
            gh api repos/${GITHUB_REPOSITORY}/git/refs -f ref="refs/tags/$TAG" -f sha="$(git rev-parse HEAD)"
            echo "Tag $TAG created via GitHub API."
          fi
