name: Tag Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags

      - name: Tag and push if new version
        run: |
          VERSION=$(jq -r .version package.json)
          TAG="v$VERSION"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. No action taken."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "$TAG"
            git push origin "$TAG"
            echo "Tag $TAG created and pushed."

            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches \
              -d "{\"event_type\":\"trigger-release\",\"client_payload\":{\"tag\":\"$TAG\"}}"
          fi
